import {supabase,sessionId,fetchState,fetchVotes,counts,paired,subscribe,labels} from './app.js';
const qs=new URLSearchParams(location.search),host=qs.get('host')||'',badge=document.querySelector('#phaseBadge'),connection=document.querySelector('#connection'),qr=document.querySelector('#qr'),participantUrl=new URL('./index.html',location.href);participantUrl.searchParams.set('session',sessionId);const urlText=participantUrl.href;let state=null;
const phaseOrder=['waiting','round1','revealed','round2','closed'],phaseText={waiting:'等待开始',round1:'第一轮判断',revealed:'补充调查信息',round2:'第二轮判断',closed:'互动已结束'};
function showMessage(text,kind=''){const el=document.querySelector('#controlMessage');el.textContent=text;el.className=`inline-message ${kind}`}
function setConnection(text,kind=''){connection.textContent=text;connection.className=`connection-bar ${kind}`}
function renderQr(){document.querySelector('#participantUrl').textContent=urlText;qr.innerHTML='';if(window.QRCode)new window.QRCode(qr,{text:urlText,width:280,height:280,colorDark:'#211611',colorLight:'#fffaf1',correctLevel:window.QRCode.CorrectLevel.M});else{const img=document.createElement('img');img.alt='参与二维码';img.src=`https://api.qrserver.com/v1/create-qr-code/?size=560x560&data=${encodeURIComponent(urlText)}`;qr.append(img);setConnection('二维码库加载失败，已切换备用二维码服务。','warn')}}
function renderPhase(){if(!state)return;badge.innerHTML=`<span class="phase-dot"></span>${phaseText[state.phase]||state.phase}`;document.querySelectorAll('.flow-step').forEach(el=>{const step=el.dataset.step;el.classList.toggle('current',step===state.phase);el.classList.toggle('done',phaseOrder.indexOf(step)<phaseOrder.indexOf(state.phase))});document.querySelectorAll('[data-action]').forEach(button=>{const a=button.dataset.action;if(a==='reset'){button.disabled=false;return}button.disabled=state.phase!==({start:'waiting',reveal:'round1',round2:'revealed',close:'round2'}[a])})}
function bars(selector,c,total){document.querySelector(selector).innerHTML=Object.entries(c).map(([k,v])=>`<div class="bar-row"><div class="bar-label"><b>${k}</b><span>${labels[k]}</span></div><div class="bar-track"><i style="width:${total?Math.round(v/total*100):0}%"></i></div><strong>${v}</strong></div>`).join('')}
async function refresh(){try{state=await fetchState();const votes=await fetchVotes(),c1=counts(votes,1),c2=counts(votes,2),p=paired(votes),total1=Object.values(c1).reduce((a,b)=>a+b,0),total2=Object.values(c2).reduce((a,b)=>a+b,0);document.querySelector('#t1').textContent=total1;document.querySelector('#t2').textContent=total2;document.querySelector('#paired').textContent=p.both;document.querySelector('#total1').textContent=`${total1} 票`;document.querySelector('#total2').textContent=`${total2} 票`;bars('#bars1',c1,total1);bars('#bars2',c2,total2);document.querySelector('#moves').innerHTML=total2?`<div class="change-line"><b>${p.both}</b><span>两轮都参加</span></div><div class="change-grid"><span>保持原选择 <b>${p.retained}</b></span><span>第二轮选A <b>${p.toA}</b></span><span>第二轮选B <b>${p.toB}</b></span><span>第二轮选C <b>${p.toC}</b></span></div>`:'第二轮开始后，这里会显示匿名判断变化。';renderPhase();if(!connection.classList.contains('warn'))setConnection(`已连接 · ${phaseText[state.phase]||state.phase}`,'good')}catch(error){console.error(error);setConnection('连接异常：请检查Supabase配置或网络。','error');showMessage(error?.message||'无法读取互动状态。','error')}}
async function control(action){if(!host){showMessage('主持人链接缺少host参数，请从完整控制台链接打开。','error');return}const button=document.querySelector(`[data-action="${action}"]`);button?.classList.add('busy');try{const {data,error}=await supabase.rpc('host_control',{p_session_id:sessionId,p_host_token:host,p_action:action});if(error||!data?.ok)throw new Error(error?.message||data?.error||'操作失败');showMessage({start:'第一轮已开始，二维码可以投屏给同学。',reveal:'调查信息已公开，请讲者读出三条材料。',round2:'第二轮已开始，同学可以保留或改选。',close:'互动已结束，准备回到总结。',reset:'本场数据已清空。'}[action]||'操作成功。','success');await refresh()}catch(error){console.error(error);showMessage(error.message,'error')}finally{button?.classList.remove('busy')}}
renderQr();document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(urlText);showMessage('参与链接已复制。','success')}catch{showMessage(urlText,'warn')}});document.querySelector('#open').addEventListener('click',()=>window.open(urlText,'_blank'));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>control(b.dataset.action)));refresh();setInterval(refresh,2500);subscribe(()=>refresh());
